services:
  api-gateway-container:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=api-gateway-container
      - EUREKA_INSTANCE_NON_SECURE_PORT=8080
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy

  proxy-client-container:
    build:
      context: ./proxy-client
      dockerfile: Dockerfile
    ports:
      - 8900:8900
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=api-gateway-container
      - EUREKA_INSTANCE_NON_SECURE_PORT=8080
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy

  order-service-container:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - 8300:8300
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=order-service-container
      - EUREKA_INSTANCE_NON_SECURE_PORT=8300
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy

  payment-service-container:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - 8400:8400
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=payment-service-container
      - EUREKA_INSTANCE_NON_SECURE_PORT=8400
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy

  product-service-container:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=product-service-container
      - EUREKA_INSTANCE_NON_SECURE_PORT=8500
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy

  shipping-service-container:
    build:
      context: ./shipping-service
      dockerfile: Dockerfile
    ports:
      - 8600:8600
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=shipping-service-container
      - EUREKA_INSTANCE_NON_SECURE_PORT=8600
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy

  user-service-container:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 8700:8700
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=user-service-container
      - EUREKA_INSTANCE_NON_SECURE_PORT=8700
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy

  favourite-service-container:
    build:
      context: ./favourite-service
      dockerfile: Dockerfile
    ports:
      - 8800:8800
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=favourite-service-container
      - EUREKA_INSTANCE_NON_SECURE_PORT=8800
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
    depends_on:
      service-discovery-container:
        condition: service_healthy
      cloud-config-container:
        condition: service_healthy

networks:
  microservices_network:
    driver: bridge
