apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
      - name: cloud-config
        image: localhost:5000/ecommerce/cloud-config:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  namespace: ecommerce
spec:
  selector:
    app: cloud-config
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  type: ClusterIP
