apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - name: service-discovery
        image: localhost:5000/ecommerce/service-discovery:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SERVER_PORT
          value: "8761"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: service-discovery
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: ecommerce
spec:
  selector:
    app: service-discovery
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
  type: ClusterIP
