pipeline {
  agent any
  stages {
    stage('Build & Unit Tests (dev)') { steps { sh 'mvn -q -pl order-service -am clean package' } }
    stage('Docker Build') { steps { sh 'docker build -f order-service/Dockerfile --build-arg PROJECT_VERSION=0.1.0 -t order-service:0.1.0 .' } }
    stage('Deploy to K8s (stage)') { when { branch 'stage' } steps { echo 'kubectl apply -n ecommerce-stage -f k8s/stage/order-service.yaml' } }
    stage('E2E on Stage') { when { branch 'stage' } steps { sh 'mvn -q -pl e2e-tests -am test' } }
    stage('Deploy to K8s (master)') { when { branch 'master' } steps { echo 'kubectl apply -n ecommerce-prod -f k8s/prod/order-service.yaml' } }
  }
}
