---
# User Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8700
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery:8761/eureka"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "user-service"
        - name: EUREKA_INSTANCE_NON_SECURE_PORT
          value: "8700"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296/"
        - name: SPRING_CLOUD_CONFIG_ALLOW_OVERRIDE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_NONE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES
          value: "true"
        readinessProbe:
          httpGet:
            path: /user-service/actuator/health
            port: 8700
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /user-service/actuator/health
            port: 8700
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
  - port: 8700
    targetPort: 8700
    protocol: TCP
    name: http
  selector:
    app: user-service
---
# Product Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: product-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8500
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery:8761/eureka"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "product-service"
        - name: EUREKA_INSTANCE_NON_SECURE_PORT
          value: "8500"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296/"
        - name: SPRING_CLOUD_CONFIG_ALLOW_OVERRIDE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_NONE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES
          value: "true"
        readinessProbe:
          httpGet:
            path: /product-service/actuator/health
            port: 8500
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /product-service/actuator/health
            port: 8500
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: product-service
spec:
  type: ClusterIP
  ports:
  - port: 8500
    targetPort: 8500
    protocol: TCP
    name: http
  selector:
    app: product-service
---
# Order Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8300
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery:8761/eureka"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "order-service"
        - name: EUREKA_INSTANCE_NON_SECURE_PORT
          value: "8300"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296/"
        - name: SPRING_CLOUD_CONFIG_ALLOW_OVERRIDE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_NONE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES
          value: "true"
        readinessProbe:
          httpGet:
            path: /order-service/actuator/health
            port: 8300
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /order-service/actuator/health
            port: 8300
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
  - port: 8300
    targetPort: 8300
    protocol: TCP
    name: http
  selector:
    app: order-service
---
# Payment Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: payment-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8400
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery:8761/eureka"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "payment-service"
        - name: EUREKA_INSTANCE_NON_SECURE_PORT
          value: "8400"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296/"
        - name: SPRING_CLOUD_CONFIG_ALLOW_OVERRIDE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_NONE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES
          value: "true"
        readinessProbe:
          httpGet:
            path: /payment-service/actuator/health
            port: 8400
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /payment-service/actuator/health
            port: 8400
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
  - port: 8400
    targetPort: 8400
    protocol: TCP
    name: http
  selector:
    app: payment-service
---
# Shipping Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping-service
        image: shipping-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8600
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery:8761/eureka"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "shipping-service"
        - name: EUREKA_INSTANCE_NON_SECURE_PORT
          value: "8600"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296/"
        - name: SPRING_CLOUD_CONFIG_ALLOW_OVERRIDE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_NONE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES
          value: "true"
        readinessProbe:
          httpGet:
            path: /shipping-service/actuator/health
            port: 8600
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /shipping-service/actuator/health
            port: 8600
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: shipping-service
spec:
  type: ClusterIP
  ports:
  - port: 8600
    targetPort: 8600
    protocol: TCP
    name: http
  selector:
    app: shipping-service
---
# Favourite Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: favourite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
      - name: favourite-service
        image: favourite-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8800
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_PROFILES_ACTIVE
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery:8761/eureka"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "favourite-service"
        - name: EUREKA_INSTANCE_NON_SECURE_PORT
          value: "8800"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296/"
        - name: SPRING_CLOUD_CONFIG_ALLOW_OVERRIDE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_NONE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES
          value: "true"
        readinessProbe:
          httpGet:
            path: /favourite-service/actuator/health
            port: 8800
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /favourite-service/actuator/health
            port: 8800
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: favourite-service
spec:
  type: ClusterIP
  ports:
  - port: 8800
    targetPort: 8800
    protocol: TCP
    name: http
  selector:
    app: favourite-service
