---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: {{ .Release.Namespace }}
  labels:
    app: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - name: service-discovery
        image: service-discovery:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8761
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: microservices-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CLOUD_CONFIG_ALLOW_OVERRIDE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_NONE
          value: "true"
        - name: SPRING_CLOUD_CONFIG_OVERRIDE_SYSTEM_PROPERTIES
          value: "true"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: {{ .Release.Namespace }}
  labels:
    app: service-discovery
spec:
  type: ClusterIP
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: http
  selector:
    app: service-discovery
