apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      containers:
      - name: proxy-client
        image: localhost:5000/ecommerce/proxy-client:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka.ecommerce:8761/eureka
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://cloud-config.ecommerce:8888
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  namespace: ecommerce
spec:
  selector:
    app: proxy-client
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
