apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yml
- configmap.yml
- zipkin.yml
- service-discovery.yml
- cloud-config.yml
- api-gateway.yml
- proxy-client.yml
- order-service.yml
- payment-service.yml
- product-service.yml
- shipping-service.yml
- user-service.yml
- favourite-service.yml
- jenkins.yml
namespace: ecommerce
